FROM python:3.10-slim-bookworm
LABEL authors="ivan"

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /sleep_diary

RUN apt-get clean && apt-get update -y && apt-get install --no-install-recommends -y \
    python3-dev

ADD ../api/requirements.txt .

RUN pip install --upgrade pip --no-cache-dir -r requirements.txt

COPY ../api /sleep_diary/api/
COPY ../common /sleep_diary/common/
COPY ../tests /sleep_diary/tests/

CMD ["bash"]