default_language_version:
    python: python3.12
default_stages: [
  pre-commit,
  pre-push,
]
fail_fast: false
repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: name-tests-test
      - id: detect-private-key

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.33.3
    hooks:
      - id: check-github-workflows
        args: ["--verbose"]

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args: [
          --in-place,
          --remove-all-unused-imports,
          --ignore-init-module-imports,
        ]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        args: [
          --config-file=mypy.ini,
        ]
        additional_dependencies: [
          "pydantic",
          "sqlalchemy[mypy]",
        ]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [ css, javascript, json ]
        args: [ --print-width=120, --tab-width=4, --html-whitespace-sensitivity=css ]
        exclude: |
          (?x)^(
            .*\.min\.(js|css)$|
            static/(js|css)/bootstrap.*|
            node_modules/.*|
            .*\.html$
          )$

  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.36.4
    hooks:
      - id: djlint-reformat
        files: \.(html|jinja|j2)$
        args: [ --indent=4, --max-line-length=120 ]
      - id: djlint
        files: \.(html|jinja|j2)$
        args: [ --max-line-length=120 ]
