default_language_version:
    python: python3.12
default_stages: [
  pre-commit,
  pre-push,
]
fail_fast: false
repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: name-tests-test
      - id: detect-private-key

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
        args: [
          --py312-plus
        ]

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args: [
          --in-place,
          --remove-all-unused-imports,
          --ignore-init-module-imports,
        ]

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: [
          --line-length=85,
          --target-version=py313,
        ]

  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: [
          --settings-path=.isort.cfg,
        ]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: [
          --config=flake8.ini,
        ]
        additional_dependencies: [
          flake8-bugbear,
          flake8-pydantic,
          flake8-black,
          flake8-isort,
          flake8-print,
          flake8-return,
          flake8-simplify,
          flake8-absolute-import,
          flake8-pytest,
          flake8-pytest-style,
          flake8-pep604,
          flake8-for-pycharm,
          flake8-useless-assert,
          flake8-unused-arguments,
          flake8-comprehensions,
          flake8-annotations-coverage,
          flake8-annotations,
          flake8-variables-names,
          flake8-eradicate,
          flake8-implicit-str-concat,
          flake8-builtins,
          flake8-warnings,
          flake8-mutable,
          flake8-pie,
          flake8-commas,
          flake8-pyproject,
          pep8-naming,
          dlint,
        ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        args: [
          --config-file=mypy.ini,
        ]
        additional_dependencies: [
          "pydantic",
          "sqlalchemy[mypy]",
        ]
