"""empty message

Revision ID: 004e88a730b0
Revises: eb6dc73824a4
Create Date: 2024-10-29 12:35:21.200208

"""

from typing import Sequence

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "004e88a730b0"
down_revision: str | None = "eb6dc73824a4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "password",
        existing_type=postgresql.BYTEA(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.create_unique_constraint("users_username_key", "users", ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_username_key", "users", type_="unique")
    op.alter_column(
        "users",
        "password",
        existing_type=sa.String(),
        type_=postgresql.BYTEA(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
