from api.routes.account import ns_account
from api.routes.auth import ns_auth
from api.routes.auth.refresh import ns_auth
from api.routes.auth.sign_in import ns_auth
from api.routes.auth.sign_out import ns_auth
from api.routes.auth.sign_up import ns_auth
from api.routes.edit import ns_edit
from api.routes.edit.delete_diary import ns_edit
from api.routes.edit.export_file import ns_edit
from api.routes.edit.import_file import ns_edit
from api.routes.main import ns_main
from api.routes.sleep import ns_sleep
from api.routes.sleep.add_note import ns_sleep
from api.routes.sleep.diary import ns_sleep
