name: Build

on:
  push:
    branches-ignore: [master, development, api-ddd]
  pull_request:
    branches: [master, development, api-ddd]

jobs:
  build:
    name: Docker Build
    runs-on: ubuntu-22.04
    env:
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Создание ключей шифрования
        run: |
          openssl genrsa -out jwt-private.pem 2048 &&
          openssl rsa -in jwt-private.pem -outform PEM -pubout -out jwt-public.pem
      - name: Скачивание PostgreSQL
        run: make pull-postgres
      - name: Запуск PostgreSQL
        run: make up-postgres
      - name: Сборка Sleep Diary
        run: make build
      - name: Запуск Sleep Diary
        run: make up